# personal

author: Haseeb Qureshi
bio: "Effective Altruist. Software engineer. @Airbnb alum. Instructor @Outco. Writer. Blockchain Believer. Former poker pro."
description: "Haseeb Qureshi is a software engineer, author, effective altruist, and former high-stakes poker pro. In his blog, he explores life, software, and altruism."
email: haseeb@haseebq.com
integrations: # Values here will be instered as USERNAME
  disqus: xhaseebq
  facebook: someguynamedhaseeb #
  github: haseeb-qureshi
  mailchimp:
  medium: hosseeb # https://medium.com/@USERNAME
  rss: rss #
  twitter: hosseeb
  youtube: INTERNETPOKERS # https://www.youtube.com/user/USERNAME/videos
name: Haseeb Qureshi

# site

baseurl: ""
cover: /assets/images/timers.jpg
domain: github.io
encoding: utf-8
lang: en
layout: default
markdown_ext: md
permalink: /:title/
timezone: UTC #America/Los_Angeles
title: haseeb qureshi
title_separator: "-"
url: https://rachelbasse.github.io

# build

exclude:
  - .editorconfig
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
gems:
  #- jekyll-archives
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  #- jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
