#
# Editing this file can easily break things. Be prepared.
#

# personal

author: Haseeb Qureshi
bio: "Managing Partner at Dragonfly Capital. Effective Altruist. Airbnb, Earn.com (acquired by Coinbase) alum. Instructor @ Bradfield. Writer. Former poker pro. Donate 33% of my income to charity."
description: "Haseeb Qureshi is an investor, software engineer, author, effective altruist, and former high-stakes poker pro. In his blog, he explores cryptocurrencies, blockchain, software, and altruism."
email: haseeb@haseebq.com
integrations: # Values here will be instered as USERNAME
  disqus: haseebq
  github: haseeb-qureshi
  gcse: # https://cse.google.com/
  medium: hosseeb # https://medium.com/@USERNAME
  rss: feed # check site-url/feed.xml
  twitter: hosseeb
  youtube: HaseebQureshi # https://www.youtube.com/user/USERNAME/videos
location: San Francisco
name: Haseeb Qureshi

# site

baseurl: ""
collections:
  pages:
    output: true
    permalink: /:title/
  tags:
    output: true
    permalink: /:path/
  years:
    output: true
    permalink: /:path/
cover: images/timers.jpg
future: true
defaults:
  -
    scope:
      path: ""
    values:
      image: haseeb-profile-pink.jpg
      layout: post
  -
    scope:
      path: _pages
      type: pages
    values:
      image: placeholder.jpg
      layout: post
  -
    scope:
      path: _posts
      type: posts
    values:
      featured: false
      image: placeholder.jpg
      layout: post
  -
    scope:
      path: _tags
      type: tags
    values:
      layout: list
      type: tags
  -
    scope:
      path: _years
      type: years
    values:
      layout: list
      type: years
domain: haseebq.com
encoding: utf-8
excerpt_separator: "\n\n"
highlighter: rouge
kramdown:
  input: GFM
lang: en
locale: en
markdown: kramdown
markdown_ext: md
permalink: /:title/
placeholder: images/placeholder.jpg
profile: images/haseeb-profile-pink.jpg
timezone: UTC #America/Los_Angeles
title: haseeb qureshi
title_separator: "-"
url: https://haseebq.com

# build

exclude:
  - .editorconfig
  - .gitignore
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sitemap
  - jemoji
