#
# Editing this file can easily break things. Be prepared for it.
#

# personal

author: Haseeb Qureshi
bio: "Effective Altruist. Software engineer. @Airbnb alum. Instructor @Outco. Writer. Blockchain Believer. Former poker pro."
description: "Haseeb Qureshi is a software engineer, author, effective altruist, and former high-stakes poker pro. In his blog, he explores life, software, and altruism."
email: haseeb@haseebq.com
integrations: # Values here will be instered as USERNAME
  disqus: xhaseebq
  facebook: someguynamedhaseeb #
  github: haseeb-qureshi
  medium: hosseeb # https://medium.com/@USERNAME
  rss: rss #
  twitter: hosseeb
  youtube: INTERNETPOKERS # https://www.youtube.com/user/USERNAME/videos
location: San Francisco
name: Haseeb Qureshi

# site

baseurl: ""
collections:
  tags:
    output: true
    permalink: /:collection/:path/
cover: images/timers.jpg
defaults:
  -
    scope:
      path: pages
      type: pages
    values:
      image: placeholder.jpg
      layout: post
      permalink: /:title/
  -
    scope:
      path: _posts
    values:
      image: placeholder.jpg
      layout: post
  -
    scope:
      path: _tags
      type: tags
    values:
      layout: list
      type: tags
domain: github.io
encoding: utf-8
excerpt_separator: "\n\n"
lang: en
markdown_ext: md
permalink: /:title/
placeholder: images/placeholder.jpg
profile: images/haseeb-profile-pink.jpg
timezone: UTC #America/Los_Angeles
title: haseeb qureshi
title_separator: "-"
url: https://rachelbasse.github.io

# build

exclude:
  - .editorconfig
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
gems:
  #- jekyll-archives
  - jekyll-avatar
  - jekyll-feed
  - jekyll-gist
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  #- jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
